name = "SCALEWAY-XBOX2"
scheduler = "slurm"

install_path = "./install_dir"
output_path = "./results"
default_partition = "batch"

mpi = "pmix"
gpus_per_node = 8
ntasks_per_node = 8
cache_docker_images_locally = true
[[partitions]]
name = "batch"
nodes = ["s01hgx[01-32],s04hgx[01-32]"]

  [[partitions.groups]]
  name = "su1"
  nodes = ["s01hgx[01-32]"]

  [[partitions.groups]]
  name = "su4"
  nodes = ["s04hgx[01-32]"]

[global_env_vars]
NCCL_IB_GID_INDEX = "3"
NCCL_IB_TIMEOUT = "20"
NCCL_IB_QPS_PER_CONNECTION = "4"
NCCL_SOCKET_IFNAME = "bond0"
NCCL_IB_TC = "96"
NCCL_IB_HCA = "mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_6,mlx5_7,mlx5_8,mlx5_9"
NCCL_IB_ADAPTIVE_ROUTING = "1"
NCCL_IB_SPLIT_DATA_ON_QPS = "0"
NCCL_IBEXT_DISABLE = "0"

UCX_IB_GID_INDEX = "3"
UCX_RNDV_SCHEME = "get_zcopy"
UCX_TLS = "rc,cuda_copy,cuda_ipc,sm"
UCX_RNDV_THRESH = "0"
UCX_IB_NUM_PATHS = "4"

UCC_CL_HIER_FULL_SBGP_TLS = "ucp"
UCC_CL_HIER_NODE_SBGP_TLS = "cuda"
UCC_CL_HIER_TUNE = "alltoall:@node_split:inf"
UCC_CLS = "basic,hier"
UCC_TL_UCP_ALLTOALL_PAIRWISE_NUM_POSTS = "16"
UCC_TL_UCP_ALLTOALLV_PAIRWISE_NUM_POSTS = "16"
UCC_TLS = "ucp,cuda"

MELLANOX_VISIBLE_DEVICES = "0,1,2,3,6,7,8,9"
CUDA_VISIBLE_DEVICES = "0,1,2,3,4,5,6,7"
